Auto-configure tasks from our API
airplanedev/action-build-and-deploy pull request #7
Opened 2021-02-04 20:16 UTC by colinking

Customers will no longer need to specify all of their tasks in their GitHub Action. Customers will instead configure tasks from the Airplane UI, and then this Action will automatically detect and build new tasks.

2021-02-04 23:30 UTC, joshma requested changes

2021-02-04 23:30 UTC, joshma commented on src/main.ts
> +  if (!tasksInput) {
Shouldn't this be the opposite? Only parse the tasksInput if `tasksInput != null`?

2021-02-04 23:33 UTC, colinking commented on src/main.ts
> +  if (!tasksInput) {
Good catch, thanks! This `if` doesn't even need to be there, it defaults to `[]` if not set.

2021-02-05 00:03 UTC, joshma approved these changes

2021-02-05 00:06 UTC, merged